apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: carbon-app-ingress
  namespace: "2401129"
 
spec:
  ingressClassName: nginx
  rules:
    - host: carbon-project.imcc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: carbon-app-service
                port:
                  number: 80