apiVersion: v1
kind: Service
metadata:
  name: carbon-app-service
  namespace: "2401129"
spec:
  selector:
    app: carbon-emission-app
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 8080 
  type: ClusterIP